import type { AuditAction, AuditResourceType } from "@domain/utils/enums.ts";
import type { Paginated, PaginationParams } from "@domain/utils/pagination.ts";
import type { RepositoryEffect } from "@domain/utils/repository.types.ts";
import type { UserId, DocumentId, AccessPolicyId } from "@domain/utils/refined.types.ts";

// ---------------------------------------------------------------------------
// AuditLogEntry — plain domain representation of an audit log row.
//
// Independent of any persistence model (Drizzle row, ORM entity, etc.) so
// that callers and controllers never import infrastructure types.
// ---------------------------------------------------------------------------

export type AuditLogEntry = {
  readonly id: string;
  readonly createdAt: string;
  readonly actorId: string;
  readonly action: AuditAction;
  readonly resourceType: AuditResourceType;
  readonly resourceId: string;
  readonly metadata: Record<string, unknown>;
};

// ---------------------------------------------------------------------------
// AuditQueryParams — inputs for the list query.
// Filters are all optional; absent filters are treated as "no filter".
// ---------------------------------------------------------------------------

export type AuditQueryParams = PaginationParams & {
  readonly resourceType?: AuditResourceType;
  readonly resourceId?: string;
};

// ---------------------------------------------------------------------------
// NewAuditLogInput — data required to persist a new audit log entry.
// The id and timestamps are generated by the repository implementation.
// ---------------------------------------------------------------------------

export type NewAuditLogInput = {
  readonly actorId: UserId;
  readonly action: AuditAction;
  readonly resourceType: AuditResourceType;
  readonly resourceId: DocumentId | AccessPolicyId;
  readonly metadata: Record<string, unknown>;
};

// ---------------------------------------------------------------------------
// IAuditRepository — persistence port for audit log queries and writes.
// ---------------------------------------------------------------------------

export interface IAuditRepository {
  listAuditLogs(params: AuditQueryParams): RepositoryEffect<Paginated<AuditLogEntry>>;
  insertAuditLog(input: NewAuditLogInput): RepositoryEffect<void>;
}
